# Generated by Django 6.0.4 on 2026-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
                ('favorite_actress', models.CharField(max_length=100)),
                ('favorite_actress_photo', models.ImageField(upload_to='images/')),
                ('favorite_singer', models.CharField(max_length=100)),
                ('favorite_singer_photo', models.ImageField(upload_to='images/')),
                ('team_name', models.CharField(max_length=100)),
                ('favorite_food', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('views', models.PositiveBigIntegerField(default=0, null=True)),
            ],
        ),
    ]
